# Encoding: UTF-8
# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms-yuzublog}
  s.version           = %q{0.0.1}
  s.description       = %q{Refinery integration for YuzuTen's Yuzublog project'}
  s.date              = %q{2011-08-09}
  s.summary           = %q{A multisite-savvy blogging engine that works with RefineryCMS}
  s.email             = %q{jason@yuzuten.com}
  s.homepage          = %q{http://www.yuzuten.com}
  s.rubyforge_project = %q{refinerycms-yuzublog}
  s.authors           = ['YuzuTen LLC', 'Jason Truesdell']
  s.license           = %q{BSD MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w()

  # Bundler
  s.add_dependency    'bundler',                    '~> 1.0'

  # Refinery CMS
  #s.add_dependency    'refinerycms-base',           '= 1.1.0'
  #s.add_dependency    'refinerycms-core',           '= 1.1.0'
  #s.add_dependency    'refinerycms-dashboard',      '= 1.1.0'
  #s.add_dependency    'refinerycms-settings',       '= 1.1.0'

  #s.add_dependency    'rails', '>= 3.1.0rc5'
  #s.add_dependency    'yuzublog'
  s.files             = [
    '.gitignore',
    'README',
    'Rakefile',
    'app',
    'app/assets',
    'app/assets/images',
    'app/assets/images/rails.png',
    'app/assets/javascripts',
    'app/assets/javascripts/application.js',
    'app/assets/stylesheets',
    'app/assets/stylesheets/application.css',
    'app/controllers',
    'app/controllers/application_controller.rb',
    'app/controllers/refinery',
    'app/controllers/refinery/yuzublog/admin',
    'app/controllers/refinery/yuzublog/admin/blogs_controller.rb',
    'app/controllers/refinery/yuzublog/admin/comments_controller.rb',
    'app/controllers/refinery/yuzublog/admin/posts_controller.rb',
    'app/helpers',
    'app/helpers/application_helper.rb',
    'app/mailers',
    'app/models',
    'app/views',
    'app/views/layouts',
    'app/views/layouts/application.html.erb',
    'app/views/refinery',
    'app/views/refinery/yuzublog/admin',
    'app/views/refinery/yuzublog/admin/blogs',
    'app/views/refinery/yuzublog/admin/blogs/_actions.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/_blog.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/_blogs.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/_form.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/_records.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/edit.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/index.html.haml',
    'app/views/refinery/yuzublog/admin/blogs/new.html.haml',
    'app/views/refinery/yuzublog/admin/comments',
    'app/views/refinery/yuzublog/admin/comments/_actions.html.haml',
    'app/views/refinery/yuzublog/admin/comments/_comment.html.haml',
    'app/views/refinery/yuzublog/admin/comments/_comments.html.haml',
    'app/views/refinery/yuzublog/admin/comments/_form.html.haml',
    'app/views/refinery/yuzublog/admin/comments/_records.html.haml',
    'app/views/refinery/yuzublog/admin/comments/edit.html.haml',
    'app/views/refinery/yuzublog/admin/comments/index.html.haml',
    'app/views/refinery/yuzublog/admin/comments/new.html.haml',
    'app/views/refinery/yuzublog/admin/posts',
    'app/views/refinery/yuzublog/admin/posts/_actions.html.haml',
    'app/views/refinery/yuzublog/admin/posts/_form.html.haml',
    'app/views/refinery/yuzublog/admin/posts/_post.html.haml',
    'app/views/refinery/yuzublog/admin/posts/_posts.html.haml',
    'app/views/refinery/yuzublog/admin/posts/_records.html.haml',
    'app/views/refinery/yuzublog/admin/posts/drafts.html.haml',
    'app/views/refinery/yuzublog/admin/posts/edit.html.haml',
    'app/views/refinery/yuzublog/admin/posts/index.html.haml',
    'app/views/refinery/yuzublog/admin/posts/new.html.haml',
    'config',
    'config/environments',
    'config/environments/development.rb',
    'config/environments/production.rb',
    'config/environments/test.rb',
    'config/locales',
    'config/locales/en.yml',
    'config/routes.rb',
    'config.ru',
    'lib',
    'lib/refinerycms-yuzublog/version.rb',
    'lib/refinerycms-yuzublog.rb',
    'lib/tasks',
    'public',
    'public/404.html',
    'public/422.html',
    'public/500.html',
    'public/favicon.ico',
    'public/robots.txt',
    'refinerycms-yuzublog.gemspec',
    'test',
    'test/fixtures',
    'test/functional',
    'test/integration',
    'test/performance',
    'test/performance/browsing_test.rb',
    'test/test_helper.rb',
    'test/unit',
    'vendor',
    'vendor/assets',
    'vendor/assets/stylesheets'
  ]
end
